[package]
name = "yobot"
version = "0.1.0"
authors = ["Martin Conte Mac Donell <martin@lyft.com>"]

[dependencies]
regex = "0.2.2"
slack = "0.18.0"
reqwest = "0.7.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
